version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
{%- if github-actions %}
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
{%- endif %}
