name: CI
on:
  push:
    branches: ["*"] # ignore pushes that are only tags
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install rust
        id: install_rust
        uses: dtolnay/rust-toolchain@stable
{%- if action-clippy or action-fmt %}
        with:
          components: {% if action-clippy %}clippy{% endif %}{% if action-clippy and action-fmt %}, {% endif %}{% if action-fmt %}rustfmt{% endif %}
{%- endif %}
{%- if action-clippy or action-test %}
      - name: Fetch cache
        uses: Swatinem/rust-cache@v1
{%- endif %}
{%- if action-clippy %}
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
{%- endif %}
{%- if action-test %}
      - name: Test
        run: cargo test --all-features
{%- endif %}
{%- if action-fmt %}
      - name: Rustfmt
{%- if action-clippy or action-test %}
        if: always() && steps.install_rust.outcome == 'success'
{%- endif %}
        run: cargo fmt -- --check
{%- endif %}
{%- if action-docs %}
      - name: Check docs
{%- if action-clippy or action-test or action-fmt %}
        if: always() && steps.install_rust.outcome == 'success'
{%- endif %}
        run: cargo doc --no-deps
{%- endif %}
