name: CI
on:
  push:
    branches: ["*"] # ignore pushes that are only tags
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install rust
        id: install_rust
        uses: dtolnay/rust-toolchain@stable
{%- if action-clippy or action-fmt %}
        with:
          components: {% if action-clippy %}clippy{% endif %}{% if action-clippy and action-fmt %}, {% endif %}{% if action-fmt %}rustfmt{% endif %}
{%- endif %}
{%- if action-clippy or action-test %}
      - name: Fetch cache
        uses: Swatinem/rust-cache@v2
{%- endif %}
{%- if action-clippy %}
      - name: Clippy
        run: {% if action-cargo-features %}|
          {% endif %}cargo clippy --all-targets {% if action-cargo-features %}--no-default-features {% endif %}-- -D warnings{% if action-cargo-features %}
          cargo clippy --all-targets --all-features -- -D warnings{% endif %}
{%- endif %}
{%- if action-test %}
      - name: Test
        run: {% if action-cargo-features %}|
          {% endif %}cargo test --no-fail-fast{% if action-cargo-features %} --no-default-features
          cargo test --no-fail-fast --all-features{% endif %}
{%- endif %}
{%- if action-fmt %}
      - name: Rustfmt
{%- if action-clippy or action-test %}
        if: always() && steps.install_rust.outcome == 'success'
{%- endif %}
        run: cargo fmt -- --check
{%- endif %}
{%- if action-docs %}
      - name: Check docs
{%- if action-clippy or action-test or action-fmt %}
        if: always() && steps.install_rust.outcome == 'success'
{%- endif %}
        run: {% if action-cargo-features %}|
        {% endif %}cargo doc --no-deps{% if action-cargo-features %}--no-default-features
        cargo doc --no-deps --all-features{% endif %}
{%- endif %}
